### ISSUE TITLE
Combobox

### ISSUE THREAD

**Issue by jeremy-holt** [magnusdanielson/au-fluent-ui#1]
Hi, 

I've just taken a quick look at the demo app and have a few questions. I've never used React, so perhaps these the questions reflect my lack of understanding of React.

1) In the combobox demo, the first example doesn't actually select anything. If you use the keyboard or mouse to select an item from the list, the text value remains `Comic Sans`.

2) In the html template, why are the first two examples `options.one-time` while the third example is `options-bind`. When would you use `one-time` or `bind`?

3) Is there any way of overriding the key from `key` to say `id`?

4) How would you select programmatically the selectedKey, i.e. load the data in `activate()` and then select the value from testOptions? Does the component accept a `matcher.bind`?

**Comment by magnusdanielson** [comment]
Hi, 

Great questions. I will update the demo site and provide answers below.

**Comment by magnusdanielson** [comment]
Demo site updated, so now it should work

1. See new version of demo site
2. `.one-time` is where you know that the React component will not update the data or it can not update the data. So properties for initialization or string literals.
3. I am not sure what you mean. `IComboBoxOption` is defined as part of fluent-ui so it can not be changed by me
4. See new version of demo site.

**Comment by jeremy-holt** [comment]
Thanks for taking the time to answer my questions.

I will take a deeper look at it now.

However the mult-select combox in the second example does not show correctly the selected items

**Comment by magnusdanielson** [comment]
For me it does. Some choices are disabled though.
![image](https://user-images.githubusercontent.com/12081481/90403101-bf792c00-e0a0-11ea-9b59-7b21fe863b57.png)

**Comment by jeremy-holt** [comment]
![image](https://user-images.githubusercontent.com/2135027/90415232-54c7f080-e0a0-11ea-9e2f-a5e67a49560b.png)

**Comment by magnusdanielson** [comment]
You are running an old version. Try to refresh your browser and make sure it loads the new bundle files if you run from the demo site. If you build it on your on machine you have to fetch and pull the latest version.

The demo error message you have in your screen shot is not part of the latest code.

**Comment by jeremy-holt** [comment]
Hi - all well now. Thanks for your help
